import Head from "next/head";
import { Container, Card, Row, Text } from "@nextui-org/react";
import Image from "next/image";
import { Header } from "../components/Header";
import Link from "next/link";
import fs from "fs/promises";
import { Footer } from "components/Footer";
import { Layout } from "components/Layout";
import { useI18N } from "context/i18n";

export default function Home({ latestComics }) {
  const { t } = useI18N();
  return (
    <div>
      <Head>
        <title>XKCD</title>
        <meta
          name="Comics for developers"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className="text-3xl font-bold text-center my-10">
          {t("LATEST_COMICS")}
        </h1>
        <section className="grid grid-cols-1 gap-5 max-w-md m-auto sm:grid-cols-2 md:grid-cols-3 ">
          {latestComics.map((comic) => {
            return (
              // console.log(comic)
              <Link href={`/comic/${comic.id}`} key={comic.id}>
                <div className="border p-2 hover:bg-slate-50 bg-slate-200 rounded-2xl m-auto cursor-pointer">
                  <h3 className="text-center font-bold text-sm my-5">
                    {comic.title}
                  </h3>
                  <Image
                    src={comic.img}
                    width="300"
                    height="300"
                    layout="intrinsic"
                    objectFit="contain"
                    alt={comic.alt}
                  />
                </div>
              </Link>
            );
          })}
        </section>
      </Layout>
    </div>
  );
}

export async function getStaticProps(context) {
  const files = await fs.readdir("./comics");

  const latestComicsfiles = files.slice(-8, files.length);

  const promisesReadFiles = latestComicsfiles.map(async (file) => {
    const content = await fs.readFile(`./comics/${file}`, "utf-8");
    return JSON.parse(content);
  });

  const latestComics = await Promise.all(promisesReadFiles);
  // console.log(latestComics);

  return {
    props: {
      latestComics,
    },
  };
}
